---
title: "Publications"
---

***Peer-reviewed publications***\
Swearingen, H., Otani, F., Siddiqui, S., Dhesi, E. (2025). Postcolonialisms in Post-Apocalyptic Landscapes: Colonially-Driven Environmental Degradation and Coloniality in Hayao Miyazaki’s Nausicaä of the Valley of the Wind. UBC Trail Six: Undergraduate Journal of Geography, Volume 19, pp. 68-76. <https://trailsix.geog.ubc.ca/volumes/current/>.


***Reports***\
Swearingen, H., Phan, M., Belec, J., Dufour, G., Kittirtanapaibool, W. (2024) Let’s Reuse-it!: Institutional
Sustainability and Faculty and Staff Reuse at UBC. UBC SEEDs Sustainability Library.
<https://sustain.ubc.ca/sites/default/files/seedslibrary/GEOG_371_%20Reuse-it%21%20User%20Experience_Final%20Report.pdf>.


***Projects***\
Swearingen, H., Chu, S. (2024). Environmental Choice Feasibility Index for the City of Vancouver. UBC
Blogs. [GIS Project Report]. <https://blogs.ubc.ca/geos370ecfi/>.

### CONFERENCES AND TALKS

***Conference Presentations***\
Swearingen, H., Brown, T. (2023). Sleep, Dreams, Creativity, and Innovation: The Sleep-Environment
Pathway of Organizational Innovation. WRDS 150 Student Conference. [Virtual], University of
British Columbia, Vancouver, BC, 2 May 2023.
